
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

    username: root
    password: root






server:
  port: 8080

mybatis-plus:
  type-enums-package: cn.was.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

